CREATE OR REPLACE VIEW evo_product_info_view_json AS
SELECT
    pc.product_id,
    pc.pagetitle,
    pc.alias,
    pc.content,
    pc.menutitle,
    pc.pub_date,
    pc.parent,
    pc.create_dttm_raw,
    pc.create_dttm,
    pc.published_dttm_raw,
    pc.published_dttm,
    pc.edited_dttm_raw,
    pc.edited_dttm,
    pc.published,
    pc.product_description,
    pc.instruction,
    pc.mnn,
    pc.mnn_lat,
    pc.code,
    pc.brand,
    pc.country,
    pc.form,
    pc.release_form,
    pc.termin,
    pc.temperature,
    pc.image,
    pc.dose,
    pc.recipe,
    pc.is_recipe,
    pc.product_insert,
    pc.product_time_register,
    pc.product_register,
    pc.product_date_register,
    pc.product_trademark,
    pc.product_price_from,
    pc.product_price_from_old,
    pc.product_price_from_percent,
    pc.product_sticker,
    pc.is_alcohol,
    pc.delivery,
    pc.is_available,
    COALESCE(
        NULLIF(pc.product_charachters_json, ''),
        JSON_OBJECT(
            'product_id', pc.product_id,
            'pagetitle', pc.pagetitle,
            'parent', pc.parent,
            'product_description', pc.product_description,
            'instruction', pc.instruction,
            'mnn', pc.mnn,
            'mnn_lat', pc.mnn_lat,
            'code', pc.code,
            'brand', pc.brand,
            'country', pc.country,
            'form', pc.form,
            'release_form', pc.release_form,
            'termin', pc.termin,
            'temperature', pc.temperature,
            'image', pc.image,
            'dose', pc.dose,
            'recipe', pc.recipe,
            'is_recipe', pc.is_recipe,
            'is_alcohol', pc.is_alcohol,
            'product_insert', pc.product_insert,
            'product_time_register', pc.product_time_register,
            'product_register', pc.product_register,
            'product_date_register', pc.product_date_register,
            'product_trademark', pc.product_trademark,
            'product_price_from', pc.product_price_from,
            'product_price_from_old', pc.product_price_from_old,
            'product_price_from_percent', pc.product_price_from_percent,
            'product_sticker', pc.product_sticker,
            'delivery', pc.delivery
        )
    ) AS product_charachters,
    pac.action_json,
    ppc.promocodes_json,
    cjc.categories_json
FROM product_cache pc
LEFT JOIN product_action_json_cache pac ON pac.product_id = pc.product_id
LEFT JOIN product_promocode_json_cache ppc ON ppc.product_id = pc.product_id
LEFT JOIN category_json_cache cjc ON cjc.product_id = pc.product_id;
