create or replace view evo_order_view_json as
select
    eco.id as order_id,
    eco.customer_id,
    eco.created_at,
    eco.updated_at,
    regexp_replace(concat('+', regexp_replace(eco.phone, '[-()_ ]', '')), '^\\++', '+') as phone,
    eco.name,
    eco.email,
    eco.amount,
    eco.currency,
    eco.status_id,
    ecos.title as status_title,
    json_unquote(json_extract(eco.fields, '$.comment')) as comment,
    json_unquote(json_extract(eco.fields, '$.agree')) as agree,
    json_unquote(json_extract(eco.fields, '$.needDelivery')) as need_delivery,
    json_unquote(json_extract(eco.fields, '$.delivery.id')) as delivery_id,
    json_unquote(json_extract(eco.fields, '$.delivery.title')) as delivery_title,
    json_unquote(json_extract(eco.fields, '$.delivery.caption')) as delivery_caption,
    json_unquote(json_extract(eco.fields, '$.delivery.price')) as delivery_price,
    json_unquote(json_extract(eco.fields, '$.delivery.city')) as delivery_city,
    json_unquote(json_extract(eco.fields, '$.delivery.street')) as delivery_street,
    json_unquote(json_extract(eco.fields, '$.delivery.house')) as delivery_house,
    json_unquote(json_extract(eco.fields, '$.delivery.entrance')) as delivery_entrance,
    json_unquote(json_extract(eco.fields, '$.delivery.floor')) as delivery_floor,
    json_unquote(json_extract(eco.fields, '$.delivery.apartment')) as delivery_apartment,
    json_unquote(json_extract(eco.fields, '$.delivery.deliveryComment')) as delivery_comment,
    json_unquote(json_extract(eco.fields, '$.payment.id')) as payment_id,
    json_unquote(json_extract(eco.fields, '$.payment.title')) as payment_title,
    json_unquote(json_extract(eco.fields, '$.payment.caption')) as payment_caption,
    json_unquote(json_extract(eco.fields, '$.sum.pricesSum')) as sum_prices,
    json_unquote(json_extract(eco.fields, '$.sum.oldPricesSum')) as sum_prices_old,
    json_unquote(json_extract(eco.fields, '$.sum.oldPricesSaleSum')) as sum_prices_sales_old,
    json_unquote(json_extract(eco.fields, '$.sum.deliverySum')) as delivery_sum,
    json_unquote(json_extract(eco.fields, '$.sum.totalSum')) as total_sum,
    json_unquote(json_extract(eco.fields, '$.online_payment_price')) as online_payment_price,
    json_unquote(json_extract(eco.fields, '$.is_paid')) as is_paid,
    json_unquote(json_extract(eco.fields, '$.delivery_method')) as delivery_method,
    json_unquote(json_extract(eco.fields, '$.delivery_method_title')) as delivery_method_title,
    json_unquote(json_extract(eco.fields, '$.payment_method')) as payment_method,
    json_unquote(json_extract(eco.fields, '$.payment_method_title')) as payment_method_title,
    json_arrayagg(
            json_object(
                    'product_id', epovj.product_id,
                    'pharmacy_id', epovj.pharmacy_id,
                    'product_title', epovj.product_title,
                    'price', epovj.price,
                    'pharmacy_price', epovj.pharmacy_price,
                    'position', epovj.position,
                    'count', epovj.count,
                    'alias', epovj.alias,
                    'mnn', epovj.mnn,
                    'code', epovj.code,
                    'brand', epovj.brand,
                    'country', epovj.country,
                    'release_form', epovj.release_form,
                    'termin', epovj.termin,
                    'temperature', epovj.temperature,
                    'image', epovj.image,
                    'dose', epovj.dose,
                    'recipe', epovj.recipe,
                    'is_recipe', epovj.is_recipe,
                    'is_alcohol', epovj.is_alcohol,
                    'product_insert', epovj.product_insert,
                    'product_time_register', epovj.product_time_register,
                    'product_register', epovj.product_register,
                    'product_date_register', epovj.product_date_register,
                    'product_trademark', epovj.product_trademark,
                    'product_sticker', epovj.product_sticker
            )
    ) order_products_json
from evo_commerce_orders eco
         inner join evo_commerce_order_statuses ecos on (eco.status_id = ecos.id)
         inner join evo_product_order_view epovj
                    on eco.id = epovj.order_id
group by
    eco.id, eco.customer_id, eco.created_at, eco.updated_at, eco.phone, eco.name, eco.email, eco.amount, eco.currency,
    eco.status_id, ecos.title, eco.fields
;