stages:
  - deploy

variables:
  DEPLOY_PATH: "/var/www/www-root/data/www/test.mobile.apteka-online.by/"

deploy:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y openssh-client sshpass
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - ls -la ./
    - sshpass -p $DEV_PASSWORD scp -r ./* $DEV_HOST:$DEPLOY_PATH
  tags:
    - base
  when: manual
