version: '3.8'

services:

    php:
        build: ./docker/php
        container_name: inlek-php
        volumes:
            - ./:/var/www
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - redis

    nginx:
        image: nginx:latest
        container_name: inlek-nginx
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    redis:
        image: redis:7
        container_name: inlek-redis
        ports:
            - "6379:6379"
